"""M6: gates, gate comments, gate decisions

Revision ID: 350c770eb519
Revises: be1f7685c4c8
Create Date: 2026-09-13 22:06:33.297779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '350c770eb519'
down_revision: Union[str, Sequence[str], None] = 'be1f7685c4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gates',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('baseline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'CONDITIONALLY_APPROVED', name='gate_status'), nullable=False),
    sa.Column('required_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_business_id'), 'gates', ['business_id'], unique=True)
    op.create_table('gate_comments',
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_comments_business_id'), 'gate_comments', ['business_id'], unique=True)
    op.create_table('gate_decisions',
    sa.Column('gate_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'CONDITIONALLY_APPROVED', name='gate_decision_type'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.String(length=4000), nullable=False),
    sa.Column('condition_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_decisions_business_id'), 'gate_decisions', ['business_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_decisions_business_id'), table_name='gate_decisions')
    op.drop_table('gate_decisions')
    op.drop_index(op.f('ix_gate_comments_business_id'), table_name='gate_comments')
    op.drop_table('gate_comments')
    op.drop_index(op.f('ix_gates_business_id'), table_name='gates')
    op.drop_table('gates')
    # ### end Alembic commands ###
