"""r2 epic b c d h manufacturing toolruns testflows partners

Revision ID: 421a4e373afd
Revises: ae82dae21f21
Create Date: 2026-09-15 22:55:00.994121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '421a4e373afd'
down_revision: Union[str, Sequence[str], None] = 'ae82dae21f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asic_partners',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_partners_business_id'), 'asic_partners', ['business_id'], unique=True)
    op.create_table('asic_partner_changes',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_template_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['asic_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_partner_changes_business_id'), 'asic_partner_changes', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_partner_changes_partner_id'), 'asic_partner_changes', ['partner_id'], unique=False)
    op.create_table('asic_lot_travelers',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('lot_ref', sa.String(length=64), nullable=False),
    sa.Column('parent_lot_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('silicon_revision', sa.String(length=32), nullable=True),
    sa.Column('mask_rev', sa.String(length=32), nullable=True),
    sa.Column('package_rev', sa.String(length=32), nullable=True),
    sa.Column('current_partner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_partner_id'], ['asic_partners.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_lot_travelers_business_id'), 'asic_lot_travelers', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_lot_travelers_lot_ref'), 'asic_lot_travelers', ['lot_ref'], unique=False)
    op.create_index(op.f('ix_asic_lot_travelers_template_id'), 'asic_lot_travelers', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_lot_travelers_variant_id'), 'asic_lot_travelers', ['variant_id'], unique=False)
    op.create_table('asic_manufacturing_options',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('foundry', sa.String(length=64), nullable=False),
    sa.Column('node', sa.String(length=64), nullable=False),
    sa.Column('wafer_size_mm', sa.Float(), nullable=True),
    sa.Column('voltage_option', sa.String(length=64), nullable=True),
    sa.Column('device_option', sa.String(length=64), nullable=True),
    sa.Column('temperature_grade', sa.String(length=32), nullable=True),
    sa.Column('package', sa.String(length=64), nullable=False),
    sa.Column('osat', sa.String(length=64), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('tech_score', sa.Integer(), nullable=True),
    sa.Column('nre', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_manufacturing_options_business_id'), 'asic_manufacturing_options', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_manufacturing_options_template_id'), 'asic_manufacturing_options', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_manufacturing_options_variant_id'), 'asic_manufacturing_options', ['variant_id'], unique=False)
    op.create_table('asic_test_flows',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('program_revision', sa.Integer(), nullable=False),
    sa.Column('silicon_revision', sa.String(length=32), nullable=False),
    sa.Column('compatible_mask_rev', sa.String(length=32), nullable=True),
    sa.Column('compatible_package_rev', sa.String(length=32), nullable=True),
    sa.Column('target', sa.String(length=24), nullable=False),
    sa.Column('cost_rate_per_site_hour', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_test_flows_business_id'), 'asic_test_flows', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_test_flows_template_id'), 'asic_test_flows', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_test_flows_variant_id'), 'asic_test_flows', ['variant_id'], unique=False)
    op.create_table('asic_tool_runs',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('design_revision', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=48), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=False),
    sa.Column('runner_class', sa.String(length=24), nullable=False),
    sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('command_profile', sa.String(length=255), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('log_uri', sa.Text(), nullable=True),
    sa.Column('report_artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('lineage_id', sa.UUID(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_tool_runs_business_id'), 'asic_tool_runs', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_tool_runs_lineage_id'), 'asic_tool_runs', ['lineage_id'], unique=False)
    op.create_index(op.f('ix_asic_tool_runs_template_id'), 'asic_tool_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_tool_runs_variant_id'), 'asic_tool_runs', ['variant_id'], unique=False)
    op.create_table('asic_trade_studies',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('option_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annual_volume', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_trade_studies_business_id'), 'asic_trade_studies', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_trade_studies_template_id'), 'asic_trade_studies', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_trade_studies_variant_id'), 'asic_trade_studies', ['variant_id'], unique=False)
    op.create_table('asic_partner_artifacts',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('lot_traveler_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['lot_traveler_id'], ['asic_lot_travelers.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['asic_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_asic_partner_artifacts_business_id'), 'asic_partner_artifacts', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_partner_artifacts_lot_traveler_id'), 'asic_partner_artifacts', ['lot_traveler_id'], unique=False)
    op.create_index(op.f('ix_asic_partner_artifacts_partner_id'), 'asic_partner_artifacts', ['partner_id'], unique=False)
    op.create_index(op.f('ix_asic_partner_artifacts_template_id'), 'asic_partner_artifacts', ['template_id'], unique=False)
    op.create_table('asic_quality_actions',
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('lot_traveler_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('lot_ref', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fa_case_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fa_case_id'], ['asic_fa_cases.id'], ),
    sa.ForeignKeyConstraint(['lot_traveler_id'], ['asic_lot_travelers.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['asic_partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_quality_actions_business_id'), 'asic_quality_actions', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_quality_actions_lot_traveler_id'), 'asic_quality_actions', ['lot_traveler_id'], unique=False)
    op.create_index(op.f('ix_asic_quality_actions_partner_id'), 'asic_quality_actions', ['partner_id'], unique=False)
    op.create_index(op.f('ix_asic_quality_actions_template_id'), 'asic_quality_actions', ['template_id'], unique=False)
    op.create_table('asic_test_flow_items',
    sa.Column('test_flow_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('site_count', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=64), nullable=True),
    sa.Column('instrument', sa.String(length=64), nullable=True),
    sa.Column('equipment_channel', sa.String(length=32), nullable=True),
    sa.Column('expected_duration_s', sa.Float(), nullable=False),
    sa.Column('requirement_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_mode_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('defect_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_flow_id'], ['asic_test_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_test_flow_items_business_id'), 'asic_test_flow_items', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_test_flow_items_test_flow_id'), 'asic_test_flow_items', ['test_flow_id'], unique=False)
    op.create_table('asic_wafer_maps',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('lot_ref', sa.String(length=64), nullable=True),
    sa.Column('wafer_ref', sa.String(length=64), nullable=True),
    sa.Column('test_flow_id', sa.UUID(), nullable=True),
    sa.Column('grid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ground_truth', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_class', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_flow_id'], ['asic_test_flows.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_wafer_maps_business_id'), 'asic_wafer_maps', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_wafer_maps_template_id'), 'asic_wafer_maps', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_wafer_maps_variant_id'), 'asic_wafer_maps', ['variant_id'], unique=False)
    op.create_table('asic_limit_changes',
    sa.Column('test_flow_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('old_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('applied_flow_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applied_flow_id'], ['asic_test_flows.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['asic_test_flow_items.id'], ),
    sa.ForeignKeyConstraint(['test_flow_id'], ['asic_test_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_limit_changes_business_id'), 'asic_limit_changes', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_limit_changes_test_flow_id'), 'asic_limit_changes', ['test_flow_id'], unique=False)
    # NOTE: autogenerate also flagged a model_cards unique-index drift — that is
    # pre-existing schema/model divergence unrelated to R2; leave model_cards alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asic_limit_changes_test_flow_id'), table_name='asic_limit_changes')
    op.drop_index(op.f('ix_asic_limit_changes_business_id'), table_name='asic_limit_changes')
    op.drop_table('asic_limit_changes')
    op.drop_index(op.f('ix_asic_wafer_maps_variant_id'), table_name='asic_wafer_maps')
    op.drop_index(op.f('ix_asic_wafer_maps_template_id'), table_name='asic_wafer_maps')
    op.drop_index(op.f('ix_asic_wafer_maps_business_id'), table_name='asic_wafer_maps')
    op.drop_table('asic_wafer_maps')
    op.drop_index(op.f('ix_asic_test_flow_items_test_flow_id'), table_name='asic_test_flow_items')
    op.drop_index(op.f('ix_asic_test_flow_items_business_id'), table_name='asic_test_flow_items')
    op.drop_table('asic_test_flow_items')
    op.drop_index(op.f('ix_asic_quality_actions_template_id'), table_name='asic_quality_actions')
    op.drop_index(op.f('ix_asic_quality_actions_partner_id'), table_name='asic_quality_actions')
    op.drop_index(op.f('ix_asic_quality_actions_lot_traveler_id'), table_name='asic_quality_actions')
    op.drop_index(op.f('ix_asic_quality_actions_business_id'), table_name='asic_quality_actions')
    op.drop_table('asic_quality_actions')
    op.drop_index(op.f('ix_asic_partner_artifacts_template_id'), table_name='asic_partner_artifacts')
    op.drop_index(op.f('ix_asic_partner_artifacts_partner_id'), table_name='asic_partner_artifacts')
    op.drop_index(op.f('ix_asic_partner_artifacts_lot_traveler_id'), table_name='asic_partner_artifacts')
    op.drop_index(op.f('ix_asic_partner_artifacts_business_id'), table_name='asic_partner_artifacts')
    op.drop_table('asic_partner_artifacts')
    op.drop_index(op.f('ix_asic_trade_studies_variant_id'), table_name='asic_trade_studies')
    op.drop_index(op.f('ix_asic_trade_studies_template_id'), table_name='asic_trade_studies')
    op.drop_index(op.f('ix_asic_trade_studies_business_id'), table_name='asic_trade_studies')
    op.drop_table('asic_trade_studies')
    op.drop_index(op.f('ix_asic_tool_runs_variant_id'), table_name='asic_tool_runs')
    op.drop_index(op.f('ix_asic_tool_runs_template_id'), table_name='asic_tool_runs')
    op.drop_index(op.f('ix_asic_tool_runs_lineage_id'), table_name='asic_tool_runs')
    op.drop_index(op.f('ix_asic_tool_runs_business_id'), table_name='asic_tool_runs')
    op.drop_table('asic_tool_runs')
    op.drop_index(op.f('ix_asic_test_flows_variant_id'), table_name='asic_test_flows')
    op.drop_index(op.f('ix_asic_test_flows_template_id'), table_name='asic_test_flows')
    op.drop_index(op.f('ix_asic_test_flows_business_id'), table_name='asic_test_flows')
    op.drop_table('asic_test_flows')
    op.drop_index(op.f('ix_asic_manufacturing_options_variant_id'), table_name='asic_manufacturing_options')
    op.drop_index(op.f('ix_asic_manufacturing_options_template_id'), table_name='asic_manufacturing_options')
    op.drop_index(op.f('ix_asic_manufacturing_options_business_id'), table_name='asic_manufacturing_options')
    op.drop_table('asic_manufacturing_options')
    op.drop_index(op.f('ix_asic_lot_travelers_variant_id'), table_name='asic_lot_travelers')
    op.drop_index(op.f('ix_asic_lot_travelers_template_id'), table_name='asic_lot_travelers')
    op.drop_index(op.f('ix_asic_lot_travelers_lot_ref'), table_name='asic_lot_travelers')
    op.drop_index(op.f('ix_asic_lot_travelers_business_id'), table_name='asic_lot_travelers')
    op.drop_table('asic_lot_travelers')
    op.drop_index(op.f('ix_asic_partner_changes_partner_id'), table_name='asic_partner_changes')
    op.drop_index(op.f('ix_asic_partner_changes_business_id'), table_name='asic_partner_changes')
    op.drop_table('asic_partner_changes')
    op.drop_index(op.f('ix_asic_partners_business_id'), table_name='asic_partners')
    op.drop_table('asic_partners')
    # ### end Alembic commands ###
