"""fa capa workflow

Revision ID: 8aaac1ba4a8b
Revises: b8f2e4a6c7d1
Create Date: 2026-09-14 15:58:29.503284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aaac1ba4a8b'
down_revision: Union[str, Sequence[str], None] = 'b8f2e4a6c7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_analyses',
    sa.Column('defect_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('analyst', sa.String(length=255), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_confirmed', sa.Boolean(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_analyses_business_id'), 'failure_analyses', ['business_id'], unique=True)
    op.create_index(op.f('ix_failure_analyses_defect_id'), 'failure_analyses', ['defect_id'], unique=False)
    op.create_table('capas',
    sa.Column('failure_analysis_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('capa_type', sa.Enum('CORRECTIVE', 'PREVENTIVE', 'BOTH', name='capa_action_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'EFFECTIVENESS_VERIFIED', 'CLOSED', name='capa_status'), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_test_run_id', sa.UUID(), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_analysis_id'], ['failure_analyses.id'], ),
    sa.ForeignKeyConstraint(['verification_test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capas_business_id'), 'capas', ['business_id'], unique=True)
    op.create_index(op.f('ix_capas_failure_analysis_id'), 'capas', ['failure_analysis_id'], unique=False)
    op.create_table('capa_events',
    sa.Column('capa_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'EFFECTIVENESS_VERIFIED', 'CLOSED', name='capa_event_type'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capa_id'], ['capas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capa_events_business_id'), 'capa_events', ['business_id'], unique=True)
    op.create_index(op.f('ix_capa_events_capa_id'), 'capa_events', ['capa_id'], unique=False)
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on
    # model_cards (a unique CONSTRAINT vs. the model's unique INDEX — same
    # effect, different catalog representation, not something this FA/CAPA
    # change touches). Deliberately left out of this revision to keep the
    # diff scoped to the new tables and avoid colliding with parallel work
    # on model_canvas.py — see AGENTS.md "FA/CAPA workflow" section.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capa_events_capa_id'), table_name='capa_events')
    op.drop_index(op.f('ix_capa_events_business_id'), table_name='capa_events')
    op.drop_table('capa_events')
    op.drop_index(op.f('ix_capas_failure_analysis_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_business_id'), table_name='capas')
    op.drop_table('capas')
    op.drop_index(op.f('ix_failure_analyses_defect_id'), table_name='failure_analyses')
    op.drop_index(op.f('ix_failure_analyses_business_id'), table_name='failure_analyses')
    op.drop_table('failure_analyses')
    # ### end Alembic commands ###
