"""asic twin v1.1 r1 tables

Revision ID: ae82dae21f21
Revises: a9f9769ac53e
Create Date: 2026-09-15 20:42:13.070330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae82dae21f21'
down_revision: Union[str, Sequence[str], None] = 'a9f9769ac53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asic_fa_cases',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('lot_ref', sa.String(length=64), nullable=True),
    sa.Column('wafer_ref', sa.String(length=64), nullable=True),
    sa.Column('die_ref', sa.String(length=64), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('repro_condition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_confirmed', sa.Boolean(), nullable=False),
    sa.Column('cause_class', sa.String(length=24), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_fa_cases_business_id'), 'asic_fa_cases', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_fa_cases_template_id'), 'asic_fa_cases', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_fa_cases_variant_id'), 'asic_fa_cases', ['variant_id'], unique=False)
    op.create_table('asic_measurement_runs',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=128), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('equipment_model', sa.String(length=128), nullable=True),
    sa.Column('firmware', sa.String(length=64), nullable=True),
    sa.Column('calibration_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('program_revision', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lot_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_asic_measurement_runs_business_id'), 'asic_measurement_runs', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_measurement_runs_template_id'), 'asic_measurement_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_measurement_runs_variant_id'), 'asic_measurement_runs', ['variant_id'], unique=False)
    op.create_table('asic_qual_plans',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('standard_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_qual_plans_business_id'), 'asic_qual_plans', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_qual_plans_template_id'), 'asic_qual_plans', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_qual_plans_variant_id'), 'asic_qual_plans', ['variant_id'], unique=False)
    op.create_table('asic_safety_items',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('asil', sa.String(length=8), nullable=True),
    sa.Column('safety_mechanism', sa.Text(), nullable=True),
    sa.Column('diagnostic_coverage_pct', sa.Float(), nullable=True),
    sa.Column('safe_state', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asic_safety_items.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_safety_items_business_id'), 'asic_safety_items', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_safety_items_template_id'), 'asic_safety_items', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_safety_items_variant_id'), 'asic_safety_items', ['variant_id'], unique=False)
    op.create_table('asic_signal_chains',
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_class', sa.String(length=24), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['asic_signal_chains.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_signal_chains_business_id'), 'asic_signal_chains', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_signal_chains_template_id'), 'asic_signal_chains', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_signal_chains_variant_id'), 'asic_signal_chains', ['variant_id'], unique=False)
    op.create_table('asic_corner_studies',
    sa.Column('signal_chain_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('n_draws', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_version', sa.String(length=64), nullable=False),
    sa.Column('source_class', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_chain_id'], ['asic_signal_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_corner_studies_business_id'), 'asic_corner_studies', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_corner_studies_signal_chain_id'), 'asic_corner_studies', ['signal_chain_id'], unique=False)
    op.create_table('asic_ecos',
    sa.Column('fa_case_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('design_rev_from', sa.String(length=32), nullable=True),
    sa.Column('design_rev_to', sa.String(length=32), nullable=True),
    sa.Column('mask_revision', sa.String(length=32), nullable=True),
    sa.Column('test_program_revision', sa.String(length=32), nullable=True),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('regression_run_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verification_run_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fa_case_id'], ['asic_fa_cases.id'], ),
    sa.ForeignKeyConstraint(['verification_run_id'], ['asic_measurement_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_ecos_business_id'), 'asic_ecos', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_ecos_fa_case_id'), 'asic_ecos', ['fa_case_id'], unique=False)
    op.create_index(op.f('ix_asic_ecos_template_id'), 'asic_ecos', ['template_id'], unique=False)
    op.create_table('asic_fa_events',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['asic_fa_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_fa_events_business_id'), 'asic_fa_events', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_fa_events_case_id'), 'asic_fa_events', ['case_id'], unique=False)
    op.create_table('asic_fault_injections',
    sa.Column('safety_item_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('stimulus', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('simulation_run_id', sa.UUID(), nullable=True),
    sa.Column('executed_by', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['safety_item_id'], ['asic_safety_items.id'], ),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_fault_injections_business_id'), 'asic_fault_injections', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_fault_injections_safety_item_id'), 'asic_fault_injections', ['safety_item_id'], unique=False)
    op.create_table('asic_fmeda_items',
    sa.Column('safety_item_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode', sa.String(length=255), nullable=False),
    sa.Column('distribution_pct', sa.Float(), nullable=False),
    sa.Column('dc_pct', sa.Float(), nullable=True),
    sa.Column('fit_rate', sa.Float(), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('formula_version', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['safety_item_id'], ['asic_safety_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_fmeda_items_business_id'), 'asic_fmeda_items', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_fmeda_items_safety_item_id'), 'asic_fmeda_items', ['safety_item_id'], unique=False)
    op.create_table('asic_qual_results',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('group', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('samples', sa.String(length=64), nullable=False),
    sa.Column('lots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pre_electrical_run_id', sa.UUID(), nullable=True),
    sa.Column('post_electrical_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failed_param', sa.String(length=128), nullable=True),
    sa.Column('fa_case_id', sa.UUID(), nullable=True),
    sa.Column('waiver_ref', sa.String(length=255), nullable=True),
    sa.Column('waiver_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fa_case_id'], ['asic_fa_cases.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['asic_qual_plans.id'], ),
    sa.ForeignKeyConstraint(['post_electrical_run_id'], ['asic_measurement_runs.id'], ),
    sa.ForeignKeyConstraint(['pre_electrical_run_id'], ['asic_measurement_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_qual_results_business_id'), 'asic_qual_results', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_qual_results_plan_id'), 'asic_qual_results', ['plan_id'], unique=False)
    # NOTE: autogenerate also flagged a unique-constraint drift on
    # model_cards.variant_id (DB has model_cards_variant_id_key, model declares
    # a plain index). That table belongs to another workstream — left alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asic_qual_results_plan_id'), table_name='asic_qual_results')
    op.drop_index(op.f('ix_asic_qual_results_business_id'), table_name='asic_qual_results')
    op.drop_table('asic_qual_results')
    op.drop_index(op.f('ix_asic_fmeda_items_safety_item_id'), table_name='asic_fmeda_items')
    op.drop_index(op.f('ix_asic_fmeda_items_business_id'), table_name='asic_fmeda_items')
    op.drop_table('asic_fmeda_items')
    op.drop_index(op.f('ix_asic_fault_injections_safety_item_id'), table_name='asic_fault_injections')
    op.drop_index(op.f('ix_asic_fault_injections_business_id'), table_name='asic_fault_injections')
    op.drop_table('asic_fault_injections')
    op.drop_index(op.f('ix_asic_fa_events_case_id'), table_name='asic_fa_events')
    op.drop_index(op.f('ix_asic_fa_events_business_id'), table_name='asic_fa_events')
    op.drop_table('asic_fa_events')
    op.drop_index(op.f('ix_asic_ecos_template_id'), table_name='asic_ecos')
    op.drop_index(op.f('ix_asic_ecos_fa_case_id'), table_name='asic_ecos')
    op.drop_index(op.f('ix_asic_ecos_business_id'), table_name='asic_ecos')
    op.drop_table('asic_ecos')
    op.drop_index(op.f('ix_asic_corner_studies_signal_chain_id'), table_name='asic_corner_studies')
    op.drop_index(op.f('ix_asic_corner_studies_business_id'), table_name='asic_corner_studies')
    op.drop_table('asic_corner_studies')
    op.drop_index(op.f('ix_asic_signal_chains_variant_id'), table_name='asic_signal_chains')
    op.drop_index(op.f('ix_asic_signal_chains_template_id'), table_name='asic_signal_chains')
    op.drop_index(op.f('ix_asic_signal_chains_business_id'), table_name='asic_signal_chains')
    op.drop_table('asic_signal_chains')
    op.drop_index(op.f('ix_asic_safety_items_variant_id'), table_name='asic_safety_items')
    op.drop_index(op.f('ix_asic_safety_items_template_id'), table_name='asic_safety_items')
    op.drop_index(op.f('ix_asic_safety_items_business_id'), table_name='asic_safety_items')
    op.drop_table('asic_safety_items')
    op.drop_index(op.f('ix_asic_qual_plans_variant_id'), table_name='asic_qual_plans')
    op.drop_index(op.f('ix_asic_qual_plans_template_id'), table_name='asic_qual_plans')
    op.drop_index(op.f('ix_asic_qual_plans_business_id'), table_name='asic_qual_plans')
    op.drop_table('asic_qual_plans')
    op.drop_index(op.f('ix_asic_measurement_runs_variant_id'), table_name='asic_measurement_runs')
    op.drop_index(op.f('ix_asic_measurement_runs_template_id'), table_name='asic_measurement_runs')
    op.drop_index(op.f('ix_asic_measurement_runs_business_id'), table_name='asic_measurement_runs')
    op.drop_table('asic_measurement_runs')
    op.drop_index(op.f('ix_asic_fa_cases_variant_id'), table_name='asic_fa_cases')
    op.drop_index(op.f('ix_asic_fa_cases_template_id'), table_name='asic_fa_cases')
    op.drop_index(op.f('ix_asic_fa_cases_business_id'), table_name='asic_fa_cases')
    op.drop_table('asic_fa_cases')
    # ### end Alembic commands ###
