"""M4: test plans/runs/measurements, correlation records

Revision ID: be1f7685c4c8
Revises: eb5900f34d0a
Create Date: 2026-09-13 21:54:42.478690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be1f7685c4c8'
down_revision: Union[str, Sequence[str], None] = 'eb5900f34d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_plans',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plans_business_id'), 'test_plans', ['business_id'], unique=True)
    op.create_table('test_runs',
    sa.Column('test_plan_id', sa.UUID(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equipment_id', sa.String(length=255), nullable=True),
    sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_business_id'), 'test_runs', ['business_id'], unique=True)
    op.create_table('correlation_records',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('max_error', sa.Float(), nullable=False),
    sa.Column('correlation_coefficient', sa.Float(), nullable=False),
    sa.Column('extrapolation_warning', sa.Boolean(), nullable=False),
    sa.Column('overlap_x_min', sa.Float(), nullable=False),
    sa.Column('overlap_x_max', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_records_business_id'), 'correlation_records', ['business_id'], unique=True)
    op.create_table('measurements',
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('x_value', sa.Float(), nullable=False),
    sa.Column('y_value', sa.Float(), nullable=False),
    sa.Column('x_unit', sa.String(length=32), nullable=False),
    sa.Column('y_unit', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_business_id'), 'measurements', ['business_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_business_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_correlation_records_business_id'), table_name='correlation_records')
    op.drop_table('correlation_records')
    op.drop_index(op.f('ix_test_runs_business_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_plans_business_id'), table_name='test_plans')
    op.drop_table('test_plans')
    # ### end Alembic commands ###
