"""r3 epic i j assumptions impact scans deviations copilot interactions

Revision ID: d6deeb514240
Revises: 421a4e373afd
Create Date: 2026-09-16 10:04:26.496849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6deeb514240'
down_revision: Union[str, Sequence[str], None] = '421a4e373afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asic_copilot_interactions',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('usecase', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=False),
    sa.Column('accepted_proposals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_copilot_interactions_business_id'), 'asic_copilot_interactions', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_copilot_interactions_input_hash'), 'asic_copilot_interactions', ['input_hash'], unique=False)
    op.create_index(op.f('ix_asic_copilot_interactions_template_id'), 'asic_copilot_interactions', ['template_id'], unique=False)
    op.create_table('asic_deviations',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('skipped', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('residual_risk', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_deviations_business_id'), 'asic_deviations', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_deviations_template_id'), 'asic_deviations', ['template_id'], unique=False)
    op.create_table('asic_assumptions',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downstream', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_assumptions_business_id'), 'asic_assumptions', ['business_id'], unique=True)
    op.create_index(op.f('ix_asic_assumptions_requirement_id'), 'asic_assumptions', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_asic_assumptions_template_id'), 'asic_assumptions', ['template_id'], unique=False)
    op.create_index(op.f('ix_asic_assumptions_variant_id'), 'asic_assumptions', ['variant_id'], unique=False)
    op.create_table('asic_assumption_events',
    sa.Column('assumption_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['asic_assumptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_assumption_events_assumption_id'), 'asic_assumption_events', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_asic_assumption_events_business_id'), 'asic_assumption_events', ['business_id'], unique=True)
    op.create_table('asic_impact_scans',
    sa.Column('assumption_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['asic_assumptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asic_impact_scans_assumption_id'), 'asic_impact_scans', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_asic_impact_scans_business_id'), 'asic_impact_scans', ['business_id'], unique=True)
    # (model_cards unique-constraint noise removed — unrelated autogenerate
    # drift, see AGENTS.md "alembic check" note; R3 touches only new tables.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asic_impact_scans_business_id'), table_name='asic_impact_scans')
    op.drop_index(op.f('ix_asic_impact_scans_assumption_id'), table_name='asic_impact_scans')
    op.drop_table('asic_impact_scans')
    op.drop_index(op.f('ix_asic_assumption_events_business_id'), table_name='asic_assumption_events')
    op.drop_index(op.f('ix_asic_assumption_events_assumption_id'), table_name='asic_assumption_events')
    op.drop_table('asic_assumption_events')
    op.drop_index(op.f('ix_asic_assumptions_variant_id'), table_name='asic_assumptions')
    op.drop_index(op.f('ix_asic_assumptions_template_id'), table_name='asic_assumptions')
    op.drop_index(op.f('ix_asic_assumptions_requirement_id'), table_name='asic_assumptions')
    op.drop_index(op.f('ix_asic_assumptions_business_id'), table_name='asic_assumptions')
    op.drop_table('asic_assumptions')
    op.drop_index(op.f('ix_asic_deviations_template_id'), table_name='asic_deviations')
    op.drop_index(op.f('ix_asic_deviations_business_id'), table_name='asic_deviations')
    op.drop_table('asic_deviations')
    op.drop_index(op.f('ix_asic_copilot_interactions_template_id'), table_name='asic_copilot_interactions')
    op.drop_index(op.f('ix_asic_copilot_interactions_input_hash'), table_name='asic_copilot_interactions')
    op.drop_index(op.f('ix_asic_copilot_interactions_business_id'), table_name='asic_copilot_interactions')
    op.drop_table('asic_copilot_interactions')
    # ### end Alembic commands ###
