"""M2: artifact version status/metadata, simulation runs, result metrics

Revision ID: e95e7b0ca370
Revises: 23e97683d68b
Create Date: 2026-09-13 20:39:38.246933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e95e7b0ca370'
down_revision: Union[str, Sequence[str], None] = '23e97683d68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('CAD_CONVERT', 'SPICE_ANALYSIS', 'MECH_MODEL', name='run_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='run_status'), nullable=False),
    sa.Column('input_artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('output_artifact_version_id', sa.UUID(), nullable=True),
    sa.Column('tool_version', sa.String(length=255), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=True),
    sa.Column('temporal_run_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['input_artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['output_artifact_version_id'], ['artifact_versions.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_business_id'), 'simulation_runs', ['business_id'], unique=True)
    op.create_table('result_metrics',
    sa.Column('simulation_run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_metrics_business_id'), 'result_metrics', ['business_id'], unique=True)
    sa.Enum('PENDING_UPLOAD', 'PROMOTED', name='artifact_version_status').create(op.get_bind(), checkfirst=True)
    op.add_column('artifact_versions', sa.Column('status', sa.Enum('PENDING_UPLOAD', 'PROMOTED', name='artifact_version_status'), nullable=False, server_default='PROMOTED'))
    op.alter_column('artifact_versions', 'status', server_default=None)
    op.add_column('artifact_versions', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('artifact_versions', 'sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('artifact_versions', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifact_versions', 'size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('artifact_versions', 'sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('artifact_versions', 'extra_metadata')
    op.drop_column('artifact_versions', 'status')
    sa.Enum(name='artifact_version_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_result_metrics_business_id'), table_name='result_metrics')
    op.drop_table('result_metrics')
    op.drop_index(op.f('ix_simulation_runs_business_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
