"""M3: add parameters column to simulation_runs

Revision ID: eb5900f34d0a
Revises: e95e7b0ca370
Create Date: 2026-09-13 21:44:12.326422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb5900f34d0a'
down_revision: Union[str, Sequence[str], None] = 'e95e7b0ca370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_runs', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'parameters')
    # ### end Alembic commands ###
